### ISSUE TITLE
SVG renderer does not always include attributes

### ISSUE THREAD

**Issue by gbdrummer** [ngnjs/chassis-lib#26]
When rendering an SVG using the chassis lib like so:

`<svg src="path/to/svg.svg" class="icon" />`

the "class" attribute is not included in the final output in some cases. For example, see Fenix filebrowser template.

**Comment by coreybutler** [comment]
This was fixed when NGN.DOM.guarantee was added, but I forgot to associate the commit with this issue. A rather extensive RegExp was created to support this, along with a basic unit test, and I can no longer recreate the issue. I'm closing since it appears to be fixed.

@gbdrummer - Reopen this if you still encounter this issue with NGN v1.1.0+
